name: coupon-study

services:
  mysql:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coupon

  redis:
    image: redis:7.0.15
    ports:
      - "6379:6379"

  redis-exporter:
    image: oliver006/redis_exporter:v1.59.0
    environment:
      REDIS_ADDR: redis://redis:6379

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

  influxdb:
    image: influxdb:1.8.10
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
