apiVersion: 1

deleteDatasources:
  - name: k6-influxdb
  - name: coupon-mysql

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s
