apiVersion: 1

deleteDatasources:
  - name: k6-influxdb

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s

  - name: coupon-mysql
    uid: mysql
    type: mysql
    url: mysql:3306
    user: root
    jsonData:
      database: coupon
    secureJsonData:
      password: "1234"
