### create coupon
POST http://localhost:8080/api/coupon
Content-Type: application/json

{
  "name": "test",
  "totalQuantity": 3
}

> {%
    client.global.set("couponId", response.body.toString());
%}

### issue userId=1
POST http://localhost:8080/api/coupon/{{couponId}}/issue/test
Content-Type: application/json

{
  "userId": 1
}

### issue userId=2
POST http://localhost:8080/api/coupon/{{couponId}}/issue/test
Content-Type: application/json

{
  "userId": 2
}

### issue userId=3
POST http://localhost:8080/api/coupon/{{couponId}}/issue/test
Content-Type: application/json

{
  "userId": 3
}

### issue userId=4
POST http://localhost:8080/api/coupon/{{couponId}}/issue/test
Content-Type: application/json

{
  "userId": 4
}

### issue userId=1 again
POST http://localhost:8080/api/coupon/{{couponId}}/issue/test
Content-Type: application/json

{
  "userId": 1
}
