name: coupon-study

services:
  mysql:
    image: mysql:8.0.34
    command: --innodb-buffer-pool-size=256M
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coupon

  redis:
    image: redis:7.0.15

  redis-exporter:
    image: oliver006/redis_exporter:v1.59.0
    environment:
      REDIS_ADDR: redis://redis:6379

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_HEAP_OPTS: "-Xms400m -Xmx400m"
    depends_on:
      - zookeeper

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.7.0
    command:
      - "--kafka.server=kafka:29092"
    restart: always
    depends_on:
      - kafka

  mysql-exporter:
    image: prom/mysqld-exporter:v0.15.1
    command:
      - "--mysqld.address=mysql:3306"
      - "--mysqld.username=root:1234"
    restart: always
    depends_on:
      - mysql

  coupon-api:
    image: eclipse-temurin:17-jre
    command: java -Xmx512m -jar /app.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coupon
      SPRING_DATA_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      - ../coupon-api/build/libs/coupon-api-0.0.1.jar:/app.jar:ro
    restart: on-failure
    depends_on:
      - mysql
      - redis
      - kafka

  coupon-consumer:
    image: eclipse-temurin:17-jre
    command: java -Xmx512m -jar /app.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coupon
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      - ../coupon-consumer/build/libs/coupon-consumer-0.0.1.jar:/app.jar:ro
    restart: on-failure
    depends_on:
      - coupon-api

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - ../monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ../monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
